add_newline = true
command_timeout = 1000

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo=false
truncation_symbol="…/"

[docker_context]
format = ""

[git_branch]
truncation_length = 15
truncation_symbol = "…"

[kubernetes]
disabled = false
format = '[⛵ $context \($namespace\)](purple) '

[cmd_duration]
disabled = true

[aws]
disabled = true

[helm]
disabled = true
